### ISSUE TITLE
问个初级问题，ProcessUtils里面的几个函数catch异常后什么都不处理，这样做是可以的吧？

### ISSUE THREAD

**Issue by DeliciousOrange** [yuzhengyang/Fork#2]
初学者，请教下异常处理的问题。望告知。

**Comment by yuzhengyang** [comment]
> 初学者，请教下异常处理的问题。望告知。

· 设计的时候，大部分异常处理都是不处理、不抛出。
· Process一般来说不需要处理异常（比如启动程序、关闭程序）
· 如果你要对特殊的异常做处理（比如提示没有权限），就要自定义的编写方法了

**Comment by DeliciousOrange** [comment]
好的，多谢指教了。
