### ISSUE TITLE
兄弟，这个工具很好用，赶紧出个core版本的

### ISSUE THREAD

**Issue by qiect** [yuzhengyang/Fork#3]

**Comment by yuzhengyang** [comment]
感谢支持~~~(^_^)   另外core的话目前先不搞它，一来是我现在搞java微服务，二来是没有应用core的场景  ……

**Comment by yuzhengyang** [comment]
> _No description provided._

感谢支持~~~(^_^) 另外core的话目前先不搞它，一来是我现在搞java微服务，二来是没有应用core的场景 ……
